tls:
  certificates:
    - certFile: /certs/wildcard.crt
      keyFile:  /certs/wildcard.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/wildcard.crt
        keyFile:  /certs/wildcard.key
